now handles multiple lines and EOF breakline

diff --git a/package b/package
--- a/package
+++ b/package
@@ -102,12 +102,20 @@ newChange="# Tag: $gitTag	Packaged on: $(date)\n"
 
 # Iterate over files by globbing
 for filepath in "$unreleased_changes_directory_path"*; do
-    [ -e "$filepath" ] || continue # avoid glob not matching
+	# avoid glob not matching
+    [ -e "$filepath" ] || continue
 
-    # strips directory path prefix off of path to file to leave only the filepath
-    trueFilename=${filepath#"$unreleased_changes_directory_path"}
+    # read file line by line
+    # -r prevents backslash escapes from being interpreted.
+	# || [[ -n $line ]] prevents the last line from being ignored if it doesn't end with a \n (since read returns a non-zero
+	# exit code when it encounters EOF).
+    while read -r line || [[ -n "$line" ]]; do
 
-    newChange="$newChange$trueFilename - $(cat "$filepath")\n"
+	    # strips directory path prefix off of path to file to leave only the filepath
+	    trueFilename=${filepath#"$unreleased_changes_directory_path"}
+	    # add to newChange
+	    newChange="$newChange$trueFilename - $line\n"
+	done < "$filepath"
 done
 newChange="$newChange\n"
 
